### ISSUE TITLE
Error code: ENOENT when running `grunt version`

### ISSUE THREAD

**Issue by badfeather** [kswedberg/grunt-version#15] opened 2015-04-02 18:30 UTC
I have the following in my gruntfile:
```
    version: {
      scss: {
        options: {
          prefix: 'Version\\:\\s'
        },
        src: [ 'assets/scss/style.scss' ]
      },
      json: {
        src: [ 'bower.json', 'package.json' ]
      }
    },
```
When I run `grunt version --verbose`, I get the following:
```
Running tasks: version

Running "version" task

Running "version:scss" (version) task
Verifying property version.scss exists in config...OK
Files: assets/scss/style.scss
Options: encoding="utf8", algorithm="md5", format=false, minify, minifyname="min", length=8, rename=false, querystring={}, manifest=false, summaryOnly=false, prefix="Version\\:\\s"
Reading assets/scss/style.scss...OK
Reading undefined...ERROR
Warning: Unable to read "undefined" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
```

Any ideas? I've tried it with the scss block commented out and still get the same "undefined" file error.

**Comment by kswedberg** [comment] 2015-04-02 18:56
Hmm. that's a strange one. I can't reproduce it here. I wonder if somehow the `pkg` option isn't getting set. Can you try explicitly setting that and see what happens?

**Comment by badfeather** [comment] 2015-04-02 21:22
Hmm, tried adding the `pkg` option like so:
```
    version: {
      options: {
        pkg: [ 'package.json' ]
      },
      scss: {
        options: {
          prefix: 'Version\\:\\s'
        },
        src: [ 'assets/scss/style.scss' ]
      },
      json: {
        src: [ 'package.json', 'bower.json' ]
      }
    },
```
Same result:
```
Running tasks: version::patch

Running "version::patch" (version) task

Running "version:scss:patch" (version) task
Verifying property version.scss exists in config...OK
Files: assets/scss/style.scss
Options: encoding="utf8", algorithm="md5", format=false, minify, minifyname="min", length=8, rename=false, querystring={}, manifest=false, summaryOnly=false, pkg=["package.json"], prefix="Version\\:\\s"
Reading assets/scss/style.scss...OK
Reading undefined...ERROR
Warning: Unable to read "undefined" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
```

**Comment by kswedberg** [comment] 2015-04-06 23:57
Do you have a link to your repo? Or maybe could you show me your gruntfile and your package.json? I can't reproduce the problem you're having with my setup, but maybe I'd be able to if I created a project that was more similar to yours?

**Comment by badfeather** [comment] 2015-04-13 18:53
I was using it on a private repo, but I've added it to a public project to try to sort it out. Would really love to get it working. https://github.com/badfeather/bad-feather-nest

Thanks for looking into it. Maybe one of my other Grunt packages is throwing it off.

**Comment by kswedberg** [comment] 2015-04-13 21:32
Aha! The problem appears to be grunt-wp-assets registering a "version" task. If you remove that one (it doesn't look like you're using it) and make sure grunt-version is added to your devDependencies, it should work.

**Comment by kswedberg** [comment] 2015-04-15 15:22
@badfeather, please let me know if removing grunt-wp-assets solves your problem, so we can close this issue. If you need both grunt-wp-assets and grunt-version, maybe you could use `grunt.task.renameTask()` to rename one of the 2 tasks before you load the other.

**Comment by badfeather** [comment] 2015-04-15 23:00
@kswedberg Sweet! You are correct. Removing grunt-wp-assets did the trick. I think I need to adjust the regex somehow to get the `/assets/scss/style.scss` version number to update, but the `bower.json` and `package.json` versions are updating as expected. Thanks for tracking that one down.

**Closed** 2015-04-16 13:53 UTC
